---
server:
  port: 9080
  servlet:
    context-path: /api-rest-jwt

---
logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.boot.autoconfigure.sql.init: DEBUG

---
spring:
  application:
    name: spring-mvc-demo
  datasource:
    #type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://angelnpo:5432/DBDEV?currentSchema=api_rest_jwt
    username: admin
    password: sasa
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 100
      connection-timeout: 30000
      max-lifetime: 300000 # 5 min
      minimumIdle: 20 # mínimo de conexiones inactivas
      idleTimeout: 300000 #Esto evita conexiones “zombi” y reduce validaciones fallidas.
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: api_rest_jwt
        order_inserts: true
        order_updates: true
        generate_statistics: false
        hbm2ddl:
          create_namespaces: true
        id:
          batch_versioned_data: true
#            new_generator_mappings: false # true for increment by 50 or (allocationSize property in mapping), false for increment one by one
        jdbc:
          batch_size: 50
          batch_versioned_data: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-location: classpath:db/schema.sql
      data-location: classpath:db/data.sql
      platform: postgres

--- # spring recommends adding the keys to custom properties
app:
    jwt:
        token-prefix: 'Bearer '
        secret: gaEbamFmubtBYCJhnfwQ_FrP1b2XCl2E6sPUvi68FeFIYa15_fB5l7LgaUszKnWtuUIBxHIcFtjtzc0Uq6l6Sg        
        expiration: 1800000 # 30 minutes
        refresh-expiration: 604800000  # 7 days refresh token
    data: # an example match configuration properties
        name: Janeth
        age: 25
